name: GitHub Pages deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4.1.3
      
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: Installing my packages
        run: yarn install --frozen-lockfile

      - name: Extract repository name
        run: echo "BASE_PATH=/$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)" >> $GITHUB_ENV

      - name: Build my App
        run: yarn build && touch ./out/.nojekyll

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: out

      - name: Checkout public branch
        uses: actions/checkout@v4.1.3
        with:
          ref: 'public'
      
      - name: Create script.sh file
        run: |
          echo '#!/bin/bash' > script.sh
          echo 'echo "VERCEL_GIT_COMMIT_REF: $VERCEL_GIT_COMMIT_REF"' >> script.sh
          echo 'if [[ "$VERCEL_GIT_COMMIT_REF" != "public" ]]; then' >> script.sh
          echo '  echo "âœ… - Build can proceed"' >> script.sh
          echo '  exit 1' >> script.sh
          echo 'else' >> script.sh
          echo '  echo "ðŸ›‘ - Build cancelled"' >> script.sh
          echo '  exit 0' >> script.sh
          echo 'fi' >> script.sh
      
      - name: Commit script.sh file
        if: ${{ success() }}
        uses: EndBug/add-and-commit@v9
        with:
            add: "script.sh"
            pull: "--rebase --autostash ."
            message: "Create script.sh"
            default_author: github_actions